name: Payme.uz Selenium CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Repositoryni yuklash
      uses: actions/checkout@v4

    - name: Python 3.11 ni o'rnatish
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Kerakli kutubxonalarni o'rnatish
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Testlarni ishga tushirish
      env:
        BASE_URL: ${{ secrets.BASE_URL }}  # GitHub Secrets dan olinadi
        HEADLESS: "true"  # CI da har doim headless
      run: |
        pytest tests/test_main_page/ \  # Testlar joylashgan papka
          --html=report.html \
          --self-contained-html \
          --base-url=${BASE_URL}

    - name: Test hisobotini saqlash
      uses: actions/upload-artifact@v4
      with:
        name: selenium-report
        path: report.html