name: Selenium UI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444

    steps:
    - name: Kodni yuklash
      uses: actions/checkout@v3

    - name: Pythonni o‘rnatish
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Kutubxonalarni o‘rnatish
      run: pip install -r requirements.txt

    - name: UI testlarni ishga tushirish
      env:
        SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub
      run: pytest tests/ --tb=short -v
